export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';

// UPDATE PROFILE
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';

// UPDATE PASSWORD
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED';
