export const CHECK_EMAIL = 'CHECK_EMAIL';
export const CHECK_EMAIL_SUCCESS = 'CHECK_EMAIL_SUCCESS';
export const CHECK_EMAIL_FAILED = 'CHECK_EMAIL_FAILED';
export const SET_CHECK_EMAIL_ERROR = 'SET_CHECK_EMAIL_ERROR';
