export const GET_DISTRICT = 'GET_DISTRICT';
export const GET_DISTRICT_SUCCESS = 'GET_DISTRICT_SUCCESS';
export const GET_DISTRICT_FAILED = 'GET_DISTRICT_FAILED';
export const SET_DISTRICT = 'SET_DISTRICT';
export const RESET_DISTRICT = 'RESET_DISTRICT';
export const GET_ONLY_DISTRICT = 'GET_ONLY_DISTRICT'
