export const GET_AVAILABLE_PAYMENT = 'GET_AVAILABLE_PAYMENT';
export const GET_AVAILABLE_PAYMENT_SUCCESS = 'GET_AVAILABLE_PAYMENT_SUCCESS';
export const GET_AVAILABLE_PAYMENT_FAILED = 'GET_AVAILABLE_PAYMENT_FAILED';
