export const GET_BANK_LIST = 'GET_BANK_LIST';
export const GET_BANK_LIST_SUCCESS = 'GET_BANK_LIST_SUCCESS';
export const GET_BANK_LIST_FAILED = 'GET_BANK_LIST_FAILED';
export const SET_BANK_LIST = 'SET_BANK_LIST';
