export const SET_REQUEST_VERIFICATION = 'SET_REQUEST_VERIFICATION';
export const SET_REQUEST_VERIFICATION_SUCCESS =
  'SET_REQUEST_VERIFICATION_SUCCESS';
export const SET_REQUEST_VERIFICATION_FAILED =
  'SET_REQUEST_VERIFICATION_FAILED';
