export const GET_TOTAL_INVOICE = 'GET_TOTAL_INVOICE';
export const GET_TOTAL_INVOICE_SUCCESS = 'GET_TOTAL_INVOICE_SUCCESS';
export const GET_TOTAL_INVOICE_FAILED = 'GET_TOTAL_INVOICE_FAILED';

export const GET_INVOICE_LIST = 'GET_INVOICE_LIST';
export const GET_INVOICE_LIST_SUCCESS = 'GET_INVOICE_LIST_SUCCESS';
export const GET_INVOICE_LIST_FAILED = 'GET_INVOICE_LIST_FAILED';
