export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILED = 'UPLOAD_IMAGE_FAILED';
export const RESET_UPLOAD_IMAGE = 'RESET_UPLOAD_IMAGE';
export const SET_UPLOAD_IMAGE = 'SET_UPLOAD_IMAGE';
