export const GET_PROVINCE = 'GET_PROVINCE';
export const GET_PROVINCE_SUCCESS = 'GET_PROVINCE_SUCCESS';
export const GET_PROVINCE_FAILED = 'GET_PROVINCE_FAILED';
export const SET_PROVINCE = 'SET_PROVINCE';
export const GET_ONLY_PROVINCE = 'GET_ONLY_PROVINCE';
 