export const SET_AUTO_COMPLETE = 'SET_AUTO_COMPLETE';
export const SET_AUTO_COMPLETE_FAILED = 'SET_AUTO_COMPLETE_FAILED';
export const SET_AUTO_COMPLETE_SUCCESS = 'SET_AUTO_COMPLETE_SUCCESS';
export const SELECT_AUTO_COMPLETE = 'SELECT_AUTO_COMPLETE';
export const SHOW_AUTO_COMPLETE = 'SHOW_AUTO_COMPLETE';
